# AURORA A1 drawing set (TechDraw, A3). Run inside FreeCAD GUI after build_aurora_a1.build().
# Each sheet is generated by its own function so a caller can stay under GUI-dispatch time limits.
import os
import time
import FreeCAD as App
import TechDraw
from FreeCAD import Vector as V

import build_aurora_a1 as A

TPL = App.getResourceDir() + "Mod/TechDraw/Templates/ISO/A3_Landscape_TD.svg"
OUT = "C:/Prj/FreeCAD_Demo_001/aurora_a1/drawings"
DATE = "2026-09-26"
JP_FONT = "Yu Gothic"
TOTAL_SHEETS = 11

TOP = (V(0, 0, 1), V(1, 0, 0))        # plan, nose to the left
SIDE = (V(0, -1, 0), V(1, 0, 0))      # right-hand elevation, nose to the left
FRONT = (V(-1, 0, 0), V(0, -1, 0))    # looking at the nose
REAR = (V(1, 0, 0), V(0, 1, 0))
ISO = (V(-1, -1, 0.8), V(0.7071, -0.7071, 0))


def _pump(objs, timeout=75.0):
    """TechDraw projects in worker threads; spin the Qt loop until every view has edges."""
    from PySide import QtWidgets
    t0 = time.time()
    pending = [o for o in objs if o.isDerivedFrom("TechDraw::DrawViewPart")]
    while pending and time.time() - t0 < timeout:
        QtWidgets.QApplication.processEvents()
        time.sleep(0.03)
        pending = [o for o in pending if len(o.getVisibleEdges()) == 0]
    return [o.Name for o in pending]


def objs(doc, names):
    return [doc.getObject(n) for n in names if doc.getObject(n) is not None]


def by_prefix(doc, *prefixes):
    return [o for o in doc.Objects if o.TypeId == "Part::Feature" and o.Name.startswith(prefixes)]


class Sheet:
    def __init__(self, doc, key, title, subtitle, number, scale_txt):
        self.doc = doc
        self.key = key
        self.number = number
        self._remove_existing()
        self.page = doc.addObject("TechDraw::DrawPage", key)
        self.tpl = doc.addObject("TechDraw::DrawSVGTemplate", key + "_Tpl")
        self.tpl.Template = TPL
        self.page.Template = self.tpl
        texts = self.tpl.EditableTexts
        vals = {"FC-Title": title, "Subtitle": subtitle, "drawing_number": "AUR-A1-%02d" % number,
                "scale": scale_txt, "AuthorName": "Claude Code (FreeCAD MCP)", "CreationDate": DATE,
                "SheetNumber": "%d / %d" % (number, TOTAL_SHEETS), "SupervisorName": "-",
                "CheckDate": "-", "Weight": "-"}
        for k, v in vals.items():
            if k in texts:
                texts[k] = v
        self.tpl.EditableTexts = texts
        self.views = []
        self.dims = []

    def _remove_existing(self):
        old = self.doc.getObject(self.key)
        if old is not None:
            _close_page_window(old)
            # removing a view also removes its dimensions, so work from names
            names = [v.Name for v in old.Views]
            tpl_name = old.Template.Name if old.Template is not None else None
            for n in names:
                if self.doc.getObject(n) is not None:
                    self.doc.removeObject(n)
            self.doc.removeObject(old.Name)
            if tpl_name and self.doc.getObject(tpl_name) is not None:
                self.doc.removeObject(tpl_name)

    def view(self, name, sources, dirs, scale, x, y, caption="", coarse=False):
        v = self.doc.addObject("TechDraw::DrawViewPart", self.key + "_" + name)
        v.CoarseView = coarse
        self.page.addView(v)
        v.Source = sources
        v.Direction, v.XDirection = dirs
        v.ScaleType = "Custom"
        v.Scale = scale
        v.X, v.Y = x, y
        v.Caption = caption
        self.views.append(v)
        return v

    def section(self, name, base, symbol, normal, origin, dirs, scale, x, y, sources=None):
        s = self.doc.addObject("TechDraw::DrawViewSection", self.key + "_" + name)
        self.page.addView(s)
        s.BaseView = base
        s.Source = sources if sources is not None else base.Source
        s.SectionNormal = normal
        s.SectionOrigin = origin
        s.Direction, s.XDirection = dirs
        s.SectionSymbol = symbol
        s.Caption = "断面 %s-%s" % (symbol, symbol)
        s.ScaleType = "Custom"
        s.Scale = scale
        s.X, s.Y = x, y
        self.views.append(s)
        return s

    def note(self, name, lines, x, y, size=3.5):
        a = self.doc.addObject("TechDraw::DrawViewAnnotation", self.key + "_" + name)
        self.page.addView(a)
        a.Text = lines
        a.Font = JP_FONT
        a.TextSize = size
        a.X, a.Y = x, y
        return a

    def compute(self, deadline=900.0):
        """Generator: recompute, then yield 'waiting' until every projection has edges.
        HLR runs in worker threads, so the caller can return to FreeCAD between yields."""
        self.doc.recompute()
        t0 = time.time()
        while time.time() - t0 < deadline:
            pending = [v for v in self.views if v.isDerivedFrom("TechDraw::DrawViewPart")
                       and len(v.getVisibleEdges()) == 0]
            if not pending:
                return []
            yield "waiting"
        return [v.Name for v in pending]

    # ---- dimensions (called after compute); placed outside the view outline ----
    def extent(self, view, horizontal=True, side=None, gap=7.0):
        d = TechDraw.makeExtentDim(view, [], 0 if horizontal else 1)
        d.FormatSpec = "%.0f"
        x0, x1, y0, y1 = _extents(view)
        if horizontal:
            d.X, d.Y = (x0 + x1) / 2, (y0 - gap) if side == "below" else (y1 + gap)
        else:
            d.X, d.Y = (x1 + gap) if side == "right" else (x0 - gap), (y0 + y1) / 2
        self.dims.append(d)
        return d

    def dist(self, view, kind, p1, p2, offset=-12.0):
        """Length dimension between two 3D model points; offset is mm beyond the outline."""
        a, b = _to_view(view, p1), _to_view(view, p2)
        d = TechDraw.makeDistanceDim(view, kind, a, b)
        d.FormatSpec = "%.1f" if abs(round(d.getRawValue()) - d.getRawValue()) > 0.05 else "%.0f"
        x0, x1, y0, y1 = _extents(view)
        if kind == "DistanceX":
            d.X, d.Y = (a.x + b.x) / 2, (y0 + offset) if offset < 0 else (y1 + offset)
        else:
            d.X, d.Y = (x0 + offset) if offset < 0 else (x1 + offset), (a.y + b.y) / 2
        self.dims.append(d)
        return d

    def export(self):
        import FreeCADGui as Gui
        import TechDrawGui
        self.doc.recompute()
        _pump(self.views, 20)
        # the template is only put into the page scene once the page window exists
        self.page.ViewObject.show()
        from PySide import QtWidgets
        for _ in range(30):
            QtWidgets.QApplication.processEvents()
            time.sleep(0.02)
        os.makedirs(OUT, exist_ok=True)
        path = os.path.join(OUT, "%02d_%s.pdf" % (self.number, self.key))
        TechDrawGui.exportPageAsPdf(self.page, path)
        try:
            TechDraw.writeDXFPage(self.page, path[:-4] + ".dxf")
        except Exception as ex:
            print("dxf failed", self.key, ex)
        _close_page_window(self.page)
        return path


def _to_view(view, p):
    """3D model point -> scaled 2D point in the view's centred coordinate frame."""
    d = view.Direction.normalize()
    xd = view.XDirection.normalize()
    yd = d.cross(xd)
    c = _centroid(view)
    q = p - c
    return V(q.dot(xd) * view.Scale, q.dot(yd) * view.Scale, 0)


def _extents(view):
    """Scaled 2D bounds of the view's sources (bbox corners projected)."""
    import Part
    bb = App.BoundBox()
    for o in view.Source:
        bb.add(o.Shape.BoundBox)
    pts = [_to_view(view, V(x, y, z)) for x in (bb.XMin, bb.XMax) for y in (bb.YMin, bb.YMax)
           for z in (bb.ZMin, bb.ZMax)]
    return (min(p.x for p in pts), max(p.x for p in pts), min(p.y for p in pts), max(p.y for p in pts))


def _close_page_window(page):
    import FreeCADGui as Gui
    mw = Gui.getMainWindow()
    from PySide import QtWidgets
    mdi = mw.findChild(QtWidgets.QMdiArea)
    if mdi is None:
        return
    for w in mdi.subWindowList():
        if w.windowTitle().startswith(page.Label):
            w.close()


def _centroid(view):
    shapes = [o.Shape for o in view.Source]
    comp = shapes[0] if len(shapes) == 1 else __import__("Part").makeCompound(shapes)
    return TechDraw.findCentroid(comp, view.Direction)


# ============================ sheets ============================
def sheet_ga(doc):
    s = Sheet(doc, "S01_GA", "AURORA A1 総組立図", "General Arrangement / 三面図", 1, "1:25")
    allp = [o for o in doc.Objects if o.TypeId == "Part::Feature"]
    body = [o for o in allp if not o.Name.startswith("Decal")]
    top = s.view("Top", body, TOP, 0.04, 150, 215, "上面図 TOP")
    side = s.view("Side", body, SIDE, 0.04, 150, 115, "側面図 SIDE")
    front = s.view("Front", body, FRONT, 0.04, 340, 215, "正面図 FRONT")
    iso = s.view("Iso", body, ISO, 0.025, 340, 125, "アイソメ ISO")
    left = yield from s.compute()
    s.extent(top, True)
    s.extent(top, False)
    s.extent(side, False)
    s.dist(side, "DistanceX", V(0, 0, 0), V(A.WHEELBASE, 0, 0), -24)
    s.extent(front, True)
    s.dist(front, "DistanceX", V(0, -A.FRONT_TYRE["track"] / 2, 0), V(0, A.FRONT_TYRE["track"] / 2, 0), -24)
    s.note("Spec", [
        "主要諸元  (図面値 / モデル値)",
        "全長 5,600 / 5,640   全幅 2,000 / 2,002   全高 950 / 965",
        "ホイールベース 3,600   トレッド F 1,620 / R 1,595",
        "タイヤ F 305/660 R18   R 405/670 R18",
        "部品 84 点 / サブアセンブリ 12   単位 mm",
    ], 100, 45, 3.5)
    return s


def sheet_section_cl(doc):
    s = Sheet(doc, "S02_CL_Section", "縦断面図 A-A", "Centreline section Y=0", 2, "1:20")
    allp = [o for o in doc.Objects if o.TypeId == "Part::Feature" and not o.Name.startswith("Decal")]
    cross = [o for o in allp if o.Shape.BoundBox.YMin < 0 < o.Shape.BoundBox.YMax]
    top = s.view("Top", cross, TOP, 0.025, 150, 225, "上面図（断面位置）")
    left = yield from s.compute()
    sec = s.section("SecA", top, "A", V(0, 1, 0), V(1700, 0, 450), SIDE, 0.05, 190, 120)
    left += yield from s.compute()
    s.extent(sec, True)
    s.extent(sec, False)
    s.note("Legend", [
        "A-A：車体中心線 (Y=0) で切断",
        "モノコック / ノーズ / エンジンカバー / パワーユニット /",
        "ギアボックス / フロア / ディフューザー / 前後ウイング",
    ], 100, 45, 3.5)
    return s


def sheet_front_wing(doc):
    s = Sheet(doc, "S03_FrontWing", "フロントウイング", "Front wing assembly", 3, "1:10 / 1:5")
    fw = by_prefix(doc, "FrontWing")
    plan = (V(0, 0, 1), V(0, -1, 0))
    front = (V(-1, 0, 0), V(0, -1, 0))
    top = s.view("Top", fw, plan, 0.1, 140, 225, "上面図")
    fr = s.view("Front", fw, front, 0.1, 140, 150, "正面図")
    side = s.view("Side", fw, SIDE, 0.2, 330, 225, "側面図 1:5")
    left = yield from s.compute()
    elements = by_prefix(doc, "FrontWing_MainPlane", "FrontWing_Flap")
    sec = s.section("SecB", top, "B", V(0, 1, 0), V(-850, 500, 150), SIDE, 0.2, 330, 140, elements)
    left += yield from s.compute()
    s.extent(top, True)
    s.extent(top, False)
    s.extent(fr, False)
    s.extent(side, True)
    s.extent(side, False)
    s.extent(sec, False)
    s.note("Tab", [
        "翼素の諸元（翼弦・迎角は 中央 → 翼端）",
        "メイン：翼弦 240→250 / 迎角 3°→6° / 逆NACA t0.11 m0.05",
        "フラップ1：翼弦 110→160 / 迎角 16°→22°",
        "フラップ2：翼弦 90→130 / 迎角 26°→32°",
        "フラップ3：翼弦 70→105 / 迎角 36°→44°",
        "スパン 2,000（エンドプレート外面）/ エンドプレート t10",
        "B-B：Y=500 で翼弦方向に切断（翼素のみ）",
    ], 90, 75, 3.2)
    return s


def sheet_rear_wing(doc):
    s = Sheet(doc, "S04_RearWing", "リアウイング", "Rear wing + DRS", 4, "1:10 / 3:20")
    rw = by_prefix(doc, "RearWing")
    plan = (V(0, 0, 1), V(0, -1, 0))
    rear = (V(1, 0, 0), V(0, 1, 0))
    top = s.view("Top", rw, plan, 0.1, 110, 235, "上面図")
    bk = s.view("Rear", rw, rear, 0.1, 110, 140, "背面図")
    side = s.view("Side", rw, SIDE, 0.15, 250, 205, "側面図 3:20")
    left = yield from s.compute()
    sec = s.section("SecC", top, "C", V(0, 1, 0), V(4300, 250, 800), SIDE, 0.15, 355, 205)
    left += yield from s.compute()
    s.extent(top, True)
    s.extent(bk, True)
    s.extent(bk, False)
    s.extent(side, True)
    s.extent(side, False)
    s.extent(sec, True)
    s.note("Tab", [
        "メインプレーン  翼弦 280  迎角 8°   逆NACA t0.13 m0.07",
        "DRS フラップ    翼弦 185  迎角 32°  逆NACA t0.10 m0.06",
        "ビームウイング  翼弦 170  迎角 12°",
        "スパン 1,050  エンドプレート 350 × 355 t10",
        "C-C：Y=250 で翼弦方向に切断",
    ], 100, 60, 3.2)
    return s


def sheet_chassis(doc):
    s = Sheet(doc, "S05_Chassis", "ノーズ・モノコック", "Survival cell + nose", 5, "1:20")
    ch = objs(doc, ["NoseCone", "Monocoque"])
    top = s.view("Top", ch, TOP, 0.05, 120, 230, "上面図", True)
    side = s.view("Side", ch, SIDE, 0.05, 120, 150, "側面図", True)
    left = yield from s.compute()
    secs = [("D", -450, 290, 225), ("E", 1200, 290, 150), ("F", 1900, 370, 150)]
    for sym, x, px, py in secs:
        sec = s.section("Sec" + sym, side, sym, V(-1, 0, 0), V(x, 0, 400), FRONT, 0.05, px, py)
    left += yield from s.compute()
    s.extent(top, True)
    s.extent(top, False)
    s.extent(side, False)
    for v in s.views[2:]:
        s.extent(v, True)
        s.extent(v, False)
    s.note("Tab", [
        "断面はスーパー楕円（|y/a|^n + |z/b|^n = 1）をロフト",
        "D-D  X=-450   ノーズ      n=2.6",
        "E-E  X=1,200  コックピット n=3.6（開口あり）",
        "F-F  X=1,900  燃料タンク部 n=3.4",
        "モノコック最大幅 680（図面値）",
    ], 100, 60, 3.2)
    return s


def sheet_bodywork(doc):
    s = Sheet(doc, "S06_Bodywork", "サイドポッド・エンジンカバー", "Bodywork + cross sections", 6, "1:20")
    bw = objs(doc, ["Sidepod_R", "Sidepod_L", "EngineCover", "Monocoque", "Floor"])
    top = s.view("Top", bw, TOP, 0.05, 120, 225, "上面図", True)
    side = s.view("Side", bw, SIDE, 0.05, 120, 140, "側面図", True)
    left = yield from s.compute()
    s.section("SecG", side, "G", V(-1, 0, 0), V(1200, 0, 300), FRONT, 0.05, 300, 215)
    s.section("SecH", side, "H", V(-1, 0, 0), V(2300, 0, 300), FRONT, 0.05, 300, 125)
    left += yield from s.compute()
    s.extent(top, True)
    s.extent(top, False)
    s.extent(side, False)
    for v in s.views[2:]:
        s.extent(v, True)
        s.extent(v, False)
    s.note("Tab", [
        "G-G  X=1,200  サイドポッド インレット直後",
        "H-H  X=2,300  コークボトル絞り込み部",
        "サイドポッドは箱型スーパー楕円 n=4.2 → 2.4 へ変化",
    ], 100, 55, 3.2)
    return s


def sheet_wheels(doc):
    s = Sheet(doc, "S07_Wheels", "ホイール・タイヤ・ブレーキ", "Wheel assemblies (FR / RR)", 7, "1:8")
    fr = by_prefix(doc, "Tyre_FR", "TyreStripe_FR", "Rim_FR", "WheelNut_FR", "BrakeDisc_FR", "BrakeCaliper_FR")
    rr = by_prefix(doc, "Tyre_RR", "TyreStripe_RR", "Rim_RR", "WheelNut_RR", "BrakeDisc_RR", "BrakeCaliper_RR")
    fs = s.view("FrontSide", fr, SIDE, 0.125, 85, 218, "フロント 側面")
    rs = s.view("RearSide", rr, SIDE, 0.125, 215, 218, "リア 側面")
    left = yield from s.compute()
    f_sec = s.section("SecJ", fs, "J", V(-1, 0, 0), V(0, 810, 330), FRONT, 0.125, 85, 122)
    r_sec = s.section("SecK", rs, "K", V(-1, 0, 0), V(A.WHEELBASE, 797.5, 335), FRONT, 0.125, 215, 122)
    left += yield from s.compute()
    for v in (fs, rs):
        s.extent(v, True)
    for v in (f_sec, r_sec):
        s.extent(v, True)
        s.extent(v, False)
    s.dist(f_sec, "DistanceY", V(0, 810, 330 - A.RIM_R), V(0, 810, 330 + A.RIM_R))
    s.dist(r_sec, "DistanceY", V(A.WHEELBASE, 797.5, 335 - A.RIM_R), V(A.WHEELBASE, 797.5, 335 + A.RIM_R))
    s.note("Tab", [
        "        タイヤ        リム     ブレーキディスク",
        "フロント 305/660 R18  Ø457.2  Ø300 × t32",
        "リア     405/670 R18  Ø457.2  Ø290 × t32",
        "J-J / K-K：車軸を含む鉛直面で切断",
    ], 340, 200, 3.2)
    return s


def sheet_suspension(doc):
    s = Sheet(doc, "S08_Suspension", "サスペンション", "Front push-rod / rear pull-rod", 8, "1:12.5")
    fs = by_prefix(doc, "FrontSuspension", "FrontUpright")
    rs = by_prefix(doc, "RearSuspension", "RearUpright", "Driveshaft")
    ff = s.view("FrontF", fs, FRONT, 0.08, 110, 215, "フロント 正面図")
    ft = s.view("FrontT", fs, (V(0, 0, 1), V(0, -1, 0)), 0.08, 110, 130, "フロント 上面図")
    rf = s.view("RearF", rs, REAR, 0.08, 300, 215, "リア 背面図")
    rt = s.view("RearT", rs, (V(0, 0, 1), V(0, -1, 0)), 0.08, 300, 130, "リア 上面図")
    left = yield from s.compute()
    for v in (ff, rf):
        s.extent(v, True)
        s.extent(v, False)
    for v in (ft, rt):
        s.extent(v, True)
    s.note("Tab", [
        "フロント：ダブルウィッシュボーン + プッシュロッド",
        "  アッパー外側 Z=510  ロア外側 Z=155  アップライト Y=±680",
        "リア：ダブルウィッシュボーン + プルロッド",
        "  アッパー外側 Z=525  ロア外側 Z=145  アップライト Y=±640",
        "アームは楕円断面 40 × 14 のフェアリング",
    ], 100, 45, 3.2)
    return s


def sheet_powerunit(doc):
    s = Sheet(doc, "S09_PowerUnit", "パワーユニット・ギアボックス", "1.6L V6 turbo hybrid + 8-speed", 9, "1:10")
    pu = by_prefix(doc, "ICE", "Turbo", "MGU", "EnergyStore", "Exhaust", "Gearbox", "RearCrash")
    side = s.view("Side", pu, SIDE, 0.1, 150, 200, "側面図")
    top = s.view("Top", pu, TOP, 0.1, 150, 110, "上面図")
    fr = s.view("Front", pu, FRONT, 0.1, 340, 200, "正面図")
    left = yield from s.compute()
    sec = s.section("SecL", side, "L", V(-1, 0, 0), V(2350, 0, 300), FRONT, 0.1, 340, 110)
    left += yield from s.compute()
    s.extent(side, True)
    s.extent(side, False)
    s.extent(top, False)
    s.extent(fr, True)
    s.extent(sec, True)
    s.note("Tab", [
        "V6 90° バンク  クランクケース 560 × 300 × 200",
        "ターボ：コンプレッサ Ø220 / タービン Ø210（MGU-H 同軸）",
        "MGU-K Ø120  エナジーストア 430 × 420 × 140",
        "L-L：X=2,350 でシリンダーバンクを切断",
    ], 100, 50, 3.2)
    return s


def build_bom_sheet(doc):
    """Spreadsheet of every part's bounding-box size; shown on sheets 10-11."""
    sh = doc.getObject("BOM")
    if sh is None:
        sh = doc.addObject("Spreadsheet::Sheet", "BOM")
    sh.clearAll()
    rows = []
    for o in doc.Objects:
        if o.TypeId != "Part::Feature":
            continue
        grp = next((p.Name for p in o.InListRecursive if p.TypeId == "App::Part" and p.Name != "AURORA_A1_Assembly"
                    and not p.Name.startswith("Wheel_")), "")
        bb = o.Shape.BoundBox
        rows.append((grp, o.Name, bb.XLength, bb.YLength, bb.ZLength, o.Shape.Volume / 1000.0))
    order = ["Chassis", "Aerodynamics", "PowerUnit", "Drivetrain", "Suspension", "Wheels", "Livery"]
    rows.sort(key=lambda r: (order.index(r[0]) if r[0] in order else 99, r[1]))
    head = ["No.", "Group", "Part", "L (X)", "W (Y)", "H (Z)", "Vol cm3"]
    for c, h in zip("ABCDEFG", head):
        sh.set(c + "1", h)
    for i, r in enumerate(rows, 2):
        sh.set("A%d" % i, str(i - 1))
        sh.set("B%d" % i, r[0])
        sh.set("C%d" % i, r[1])
        sh.set("D%d" % i, "%.0f" % r[2])
        sh.set("E%d" % i, "%.0f" % r[3])
        sh.set("F%d" % i, "%.0f" % r[4])
        sh.set("G%d" % i, "%.0f" % r[5])
    doc.recompute()
    return sh, len(rows)


def sheet_bom(doc, part):
    sh, n = build_bom_sheet(doc)
    half = (n + 1) // 2
    r0, r1 = (2, half + 1) if part == 1 else (half + 2, n + 1)
    # each page gets its own sheet (header + its rows) so the header repeats cleanly
    name = "BOM_%d" % part
    page_sheet = doc.getObject(name) or doc.addObject("Spreadsheet::Sheet", name)
    page_sheet.clearAll()
    for c in "ABCDEFG":
        page_sheet.set(c + "1", sh.getContents(c + "1"))
    for out_r, src_r in enumerate(range(r0, r1 + 1), 2):
        for c in "ABCDEFG":
            page_sheet.set("%s%d" % (c, out_r), sh.getContents("%s%d" % (c, src_r)))
    s = Sheet(doc, "S%02d_BOM%d" % (9 + part, part), "部品表 (%d/2)" % part,
              "Parts list: bounding box mm / volume", 9 + part, "-")
    tv = doc.addObject("TechDraw::DrawViewSpreadsheet", s.key + "_Table")
    s.page.addView(tv)
    tv.Source = page_sheet
    tv.CellStart = "A1"
    tv.CellEnd = "G%d" % (r1 - r0 + 2)
    for col, w in zip("ABCDEFG", (40, 110, 230, 70, 70, 70, 90)):
        page_sheet.setColumnWidth(col, w)
    tv.TextSize = 11.0
    tv.Scale = 0.62
    tv.X, tv.Y = 160, 165
    s.doc.recompute()
    if False:
        yield
    return s


def sheet_bom1(doc):
    return (yield from sheet_bom(doc, 1))


def sheet_bom2(doc):
    return (yield from sheet_bom(doc, 2))


SHEETS = [sheet_ga, sheet_section_cl, sheet_front_wing, sheet_rear_wing, sheet_chassis, sheet_bodywork,
          sheet_wheels, sheet_suspension, sheet_powerunit, sheet_bom1, sheet_bom2]
_JOBS = {}


def step(i, budget=60.0):
    """Advance sheet i for at most `budget` seconds of GUI time; call again until it reports done.
    Between calls FreeCAD's worker threads keep computing the projections."""
    from PySide import QtWidgets
    doc = App.getDocument(A.DOC_NAME)
    job = _JOBS.get(i)
    if job is None:
        job = _JOBS[i] = {"gen": SHEETS[i](doc), "t0": time.time()}
    t = time.time()
    try:
        while time.time() - t < budget:
            if next(job["gen"]) == "waiting":
                QtWidgets.QApplication.processEvents()
                time.sleep(0.05)
    except StopIteration as done:
        del _JOBS[i]
        s = done.value
        path = s.export()
        return {"sheet": s.key, "pdf": path, "sec": round(time.time() - job["t0"], 1), "done": True}
    return {"sheet": i, "done": False, "elapsed": round(time.time() - job["t0"], 1)}


def run(i):
    r = step(i, 80.0)
    return r
